#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import logging
from pathlib import Path
import sys
from typing import Any, Sequence

import lightgbm as lgb
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.train_baseline import (
    DEFAULT_PARAMS,
    compute_metrics,
    load_flood_risk,
    load_h3_features,
    load_hex2vec_embeddings,
    load_transit_stops,
    prepare_features,
)
from src.config.mlflow_config import (
    DEFAULT_TAGS,
    MLFLOW_TRACKING_URI,
    get_experiment_name,
)
from src.utils.mlflow_utils import (
    build_standard_run_context,
    log_artifact_safe,
    log_metrics_safe,
    log_params_safe,
    log_standard_run_context,
    mlflow_run,
    set_tag_safe,
)

DEFAULT_SOURCE_WEIGHTS = {
    "treasury": 1.0,
    "baania": 1.0,
    "hipflat": 1.0,
    "legacy_bania": 1.0,
}

CATEGORICAL_COLUMNS = ("source_site", "property_type", "district")

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
BENCHMARK_DIR = DATA_DIR / "benchmarks"
DEFAULT_DATASET_PATH = BENCHMARK_DIR / "combined_sales_v1.parquet"
DEFAULT_SPLIT_PATH = BENCHMARK_DIR / "combined_sales_v1_grouped_cv_splits.parquet"
DEFAULT_IMAGE_EMBEDDINGS_PATH = BENCHMARK_DIR / "listing_image_embeddings_v1.parquet"
DEFAULT_OUTPUT_DIR = BASE_DIR / "models" / "combined_price"

COMMON_FEATURES = [
    "area_sqm",
    "floors",
    "lat",
    "lon",
]

LISTING_METADATA_FEATURES = [
    "bedrooms",
    "bathrooms",
    "parking_spaces",
    "facility_count",
    "developer_present",
    "unit_count",
    "unit_type_count",
    "title_length",
    "highlight_length",
    "detail_length",
    "has_images",
    "image_count",
    "has_uploaded_images",
    "uploaded_image_count",
    "has_video",
]

SOURCE_AWARE_FEATURES = [
    "source_type_is_listing",
    "source_site_encoded",
    "property_type_encoded",
    "district_encoded",
]

IMAGE_EMBEDDING_PREFIX = "img_emb_"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train combined Treasury + listing price model with MLflow"
    )
    parser.add_argument(
        "--stages",
        type=str,
        default="C1,C2,C3,C4,C5",
        help="Comma-separated stage list, e.g. C5 or C4,C5",
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        default=DEFAULT_DATASET_PATH,
        help="Combined dataset parquet path",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for metrics and artifacts",
    )
    parser.add_argument(
        "--split-artifact",
        type=Path,
        default=DEFAULT_SPLIT_PATH,
        help="Grouped split parquet generated by build_combined_grouped_split.py",
    )
    parser.add_argument(
        "--dataset-version",
        type=str,
        default="combined_sales_v1",
        help="Dataset version for MLflow metadata",
    )
    parser.add_argument(
        "--experiment",
        type=str,
        default=None,
        help="MLflow experiment name",
    )
    parser.add_argument(
        "--run-name",
        type=str,
        default=None,
        help="MLflow run name",
    )
    parser.add_argument(
        "--tracking-uri",
        type=str,
        default=MLFLOW_TRACKING_URI,
        help="MLflow tracking URI override",
    )
    parser.add_argument(
        "--cv-folds",
        type=int,
        default=5,
        help="Number of grouped folds",
    )
    parser.add_argument(
        "--max-listing-test-groups",
        type=int,
        default=1,
        help="Max listing date groups per fold kept as validation",
    )
    parser.add_argument(
        "--source-weights-json",
        type=Path,
        default=None,
        help="Optional JSON file mapping source_site to training sample weight",
    )
    parser.add_argument(
        "--pretrain-dataset",
        type=Path,
        default=None,
        help="Optional pretraining dataset parquet path used before fold-level fine-tuning",
    )
    parser.add_argument(
        "--pretrain-source-weights-json",
        type=Path,
        default=None,
        help="Optional JSON file mapping source_site to pretraining sample weight",
    )
    parser.add_argument(
        "--pretrain-n-estimators",
        type=int,
        default=300,
        help="Number of trees used in the pretraining stage",
    )
    parser.add_argument(
        "--finetune-n-estimators",
        type=int,
        default=300,
        help="Max number of additional trees used during fold-level fine-tuning",
    )
    parser.add_argument(
        "--image-embeddings",
        type=Path,
        default=DEFAULT_IMAGE_EMBEDDINGS_PATH,
        help="Optional listing-level image embedding parquet keyed by row_id",
    )
    return parser.parse_args()


def load_source_weights(weights_path: Path | None) -> dict[str, float]:
    weights = DEFAULT_SOURCE_WEIGHTS.copy()
    if weights_path is None:
        return weights
    payload = json.loads(weights_path.read_text(encoding="utf-8"))
    for key, value in payload.items():
        weights[str(key)] = float(value)
    return weights


def build_sample_weights(
    df: pd.DataFrame, source_weights: dict[str, float] | None
) -> np.ndarray | None:
    if source_weights is None or len(source_weights) == 0:
        return None
    weights = df["source_site"].map(
        lambda value: float(source_weights.get(str(value), 1.0))
    )
    return weights.to_numpy(dtype=float)


def build_category_maps(dfs: Sequence[pd.DataFrame]) -> dict[str, dict[str, int]]:
    category_maps: dict[str, dict[str, int]] = {}
    for column in CATEGORICAL_COLUMNS:
        values: set[str] = set()
        for df in dfs:
            if column not in df.columns:
                continue
            values.update(df[column].fillna("unknown").astype(str).unique().tolist())
        ordered = sorted(values)
        category_maps[column] = {value: index for index, value in enumerate(ordered)}
    return category_maps


def encode_categoricals(
    df: pd.DataFrame, category_maps: dict[str, dict[str, int]] | None = None
) -> pd.DataFrame:
    result = df.copy()
    result["source_type_is_listing"] = (result["source_type"] == "listing").astype(int)

    maps = category_maps or build_category_maps([result])
    for column in CATEGORICAL_COLUMNS:
        mapping = maps[column]
        normalized = result[column].fillna("unknown").astype(str)
        fallback = len(mapping)
        result[f"{column}_encoded"] = normalized.map(
            lambda value: mapping.get(value, fallback)
        ).astype(int)
    return result


def augment_geo_features(df: pd.DataFrame, use_hex2vec: bool) -> pd.DataFrame:
    geo_input = df.copy()
    geo_input["district"] = geo_input["district"].fillna("unknown")
    geo_input["building_style_desc"] = geo_input["property_type"].fillna("unknown")
    geo_input["no_of_floor"] = geo_input["floors"]
    geo_input["total_price"] = geo_input["target_price_thb"]
    geo_input["log_price"] = geo_input["target_log_price"]

    h3_features = load_h3_features()
    hex2vec = load_hex2vec_embeddings() if use_hex2vec else None
    flood_risk = load_flood_risk()
    transit_stops = load_transit_stops()
    return prepare_features(geo_input, h3_features, hex2vec, flood_risk, transit_stops)


def add_missing_flags(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    result = df.copy()
    for column in columns:
        result[f"{column}_missing"] = result[column].isna().astype(int)
    return result


def merge_image_embeddings(
    df: pd.DataFrame,
    image_embeddings_path: Path | None,
) -> pd.DataFrame:
    result = df.copy()
    if image_embeddings_path is None or not image_embeddings_path.exists():
        result["has_image_embedding"] = 0
        result["image_embedding_count"] = 0
        return result

    emb_df = pd.read_parquet(image_embeddings_path)
    if "row_id" not in emb_df.columns:
        raise ValueError("Image embeddings artifact must include row_id")
    emb_cols = [
        column for column in emb_df.columns if column.startswith(IMAGE_EMBEDDING_PREFIX)
    ]
    keep_cols = ["row_id", "has_image_embedding", "image_embedding_count"] + emb_cols
    available_cols = [column for column in keep_cols if column in emb_df.columns]
    if len(emb_cols) == 0:
        return result

    if "has_image_embedding" not in available_cols:
        emb_df["has_image_embedding"] = 1
        available_cols.append("has_image_embedding")
    if "image_embedding_count" not in available_cols:
        emb_df["image_embedding_count"] = 1
        available_cols.append("image_embedding_count")

    merged = result.merge(emb_df[available_cols], on="row_id", how="left")

    if "has_image_embedding" in merged.columns:
        merged["has_image_embedding"] = (
            pd.to_numeric(merged["has_image_embedding"], errors="coerce")
            .fillna(0)
            .astype(int)
        )
    elif "has_image_embedding_y" in merged.columns:
        merged["has_image_embedding"] = (
            pd.to_numeric(merged["has_image_embedding_y"], errors="coerce")
            .fillna(0)
            .astype(int)
        )
    else:
        merged["has_image_embedding"] = 0

    if "image_embedding_count" in merged.columns:
        merged["image_embedding_count"] = (
            pd.to_numeric(merged["image_embedding_count"], errors="coerce")
            .fillna(0)
            .astype(int)
        )
    elif "image_embedding_count_y" in merged.columns:
        merged["image_embedding_count"] = (
            pd.to_numeric(merged["image_embedding_count_y"], errors="coerce")
            .fillna(0)
            .astype(int)
        )
    else:
        merged["image_embedding_count"] = 0
    for column in emb_cols:
        merged[column] = pd.to_numeric(merged[column], errors="coerce").fillna(0.0)
    return merged


def build_feature_set(
    df: pd.DataFrame,
    stage: str,
    category_maps: dict[str, dict[str, int]] | None = None,
) -> tuple[pd.DataFrame, list[str]]:
    result = encode_categoricals(df, category_maps=category_maps)
    result = add_missing_flags(
        result,
        [
            "area_sqm",
            "floors",
            "land_area",
            "building_age",
            "bedrooms",
            "bathrooms",
            "parking_spaces",
        ],
    )

    feature_cols: list[str] = []
    if stage == "C1":
        feature_cols = COMMON_FEATURES.copy()
    elif stage == "C2":
        feature_cols = (
            COMMON_FEATURES
            + SOURCE_AWARE_FEATURES
            + [
                "area_sqm_missing",
                "floors_missing",
            ]
        )
    elif stage == "C3":
        result = augment_geo_features(result, use_hex2vec=False)
        geo_features = [
            "dist_to_cbd_min",
            "dist_to_bts",
            "dist_to_siam_paragon",
            "dist_to_asoke",
            "dist_to_silom",
            "poi_school",
            "poi_transit_stop",
            "poi_hospital",
            "poi_mall",
            "poi_restaurant",
            "poi_cafe",
            "poi_supermarket",
            "poi_park",
            "poi_temple",
            "poi_total",
            "transit_total",
            "property_count",
            "flood_risk",
        ]
        feature_cols = (
            COMMON_FEATURES
            + SOURCE_AWARE_FEATURES
            + geo_features
            + [
                "area_sqm_missing",
                "floors_missing",
                "land_area_missing",
                "building_age_missing",
            ]
        )
    elif stage == "C4":
        result = augment_geo_features(result, use_hex2vec=True)
        hex_cols = [column for column in result.columns if column.startswith("emb_")]
        geo_features = [
            "dist_to_cbd_min",
            "dist_to_bts",
            "dist_to_siam_paragon",
            "dist_to_asoke",
            "dist_to_silom",
            "poi_school",
            "poi_transit_stop",
            "poi_hospital",
            "poi_mall",
            "poi_restaurant",
            "poi_cafe",
            "poi_supermarket",
            "poi_park",
            "poi_temple",
            "poi_total",
            "transit_total",
            "property_count",
            "flood_risk",
        ]
        feature_cols = (
            COMMON_FEATURES
            + SOURCE_AWARE_FEATURES
            + geo_features
            + hex_cols
            + [
                "area_sqm_missing",
                "floors_missing",
                "land_area_missing",
                "building_age_missing",
            ]
        )
    elif stage == "C5":
        result = augment_geo_features(result, use_hex2vec=True)
        hex_cols = [column for column in result.columns if column.startswith("emb_")]
        geo_features = [
            "dist_to_cbd_min",
            "dist_to_bts",
            "dist_to_siam_paragon",
            "dist_to_asoke",
            "dist_to_silom",
            "poi_school",
            "poi_transit_stop",
            "poi_hospital",
            "poi_mall",
            "poi_restaurant",
            "poi_cafe",
            "poi_supermarket",
            "poi_park",
            "poi_temple",
            "poi_total",
            "transit_total",
            "property_count",
            "flood_risk",
        ]
        feature_cols = (
            COMMON_FEATURES
            + SOURCE_AWARE_FEATURES
            + geo_features
            + hex_cols
            + LISTING_METADATA_FEATURES
            + [
                "area_sqm_missing",
                "floors_missing",
                "land_area_missing",
                "building_age_missing",
                "bedrooms_missing",
                "bathrooms_missing",
                "parking_spaces_missing",
            ]
        )
    elif stage == "C5I":
        result = augment_geo_features(result, use_hex2vec=True)
        hex_cols = [column for column in result.columns if column.startswith("emb_")]
        image_cols = [
            column
            for column in result.columns
            if column.startswith(IMAGE_EMBEDDING_PREFIX)
        ]
        geo_features = [
            "dist_to_cbd_min",
            "dist_to_bts",
            "dist_to_siam_paragon",
            "dist_to_asoke",
            "dist_to_silom",
            "poi_school",
            "poi_transit_stop",
            "poi_hospital",
            "poi_mall",
            "poi_restaurant",
            "poi_cafe",
            "poi_supermarket",
            "poi_park",
            "poi_temple",
            "poi_total",
            "transit_total",
            "property_count",
            "flood_risk",
        ]
        feature_cols = (
            COMMON_FEATURES
            + SOURCE_AWARE_FEATURES
            + geo_features
            + hex_cols
            + LISTING_METADATA_FEATURES
            + [
                "has_image_embedding",
                "image_embedding_count",
            ]
            + image_cols
            + [
                "area_sqm_missing",
                "floors_missing",
                "land_area_missing",
                "building_age_missing",
                "bedrooms_missing",
                "bathrooms_missing",
                "parking_spaces_missing",
            ]
        )
    else:
        raise ValueError(f"Unsupported stage: {stage}")

    available = [column for column in feature_cols if column in result.columns]
    return result, available


def assign_time_groups(df: pd.DataFrame) -> pd.DataFrame:
    result = df.copy()
    treasury_mask = result["source_type"] == "treasury"
    listing_mask = result["source_type"] == "listing"
    result.loc[treasury_mask, "time_group"] = (
        result.loc[treasury_mask, "event_date"]
        .dt.tz_localize(None)
        .dt.to_period("Q")
        .astype(str)
    )
    result.loc[listing_mask, "time_group"] = (
        result.loc[listing_mask, "event_date"]
        .dt.tz_localize(None)
        .dt.to_period("D")
        .astype(str)
    )
    result["time_group"] = result["time_group"].fillna("unknown")
    return result


def stable_fold(value: str, n_folds: int) -> int:
    digest = hashlib.md5(value.encode("utf-8"), usedforsecurity=False).hexdigest()
    return int(digest[:8], 16) % n_folds


def assign_cv_folds(df: pd.DataFrame, n_folds: int) -> pd.DataFrame:
    result = assign_time_groups(df)
    result["cv_fold"] = -1

    treasury_mask = result["source_type"] == "treasury"
    treasury_groups = sorted(result.loc[treasury_mask, "time_group"].unique())
    treasury_fold_map = {
        group: index % n_folds for index, group in enumerate(treasury_groups)
    }
    result.loc[treasury_mask, "cv_fold"] = result.loc[treasury_mask, "time_group"].map(
        treasury_fold_map
    )

    listing_mask = result["source_type"] == "listing"
    result.loc[listing_mask, "cv_fold"] = result.loc[
        listing_mask, "duplicate_group"
    ].map(lambda value: stable_fold(str(value), n_folds))

    result["cv_fold"] = result["cv_fold"].astype(int)
    return result


def load_split_artifact(split_artifact: Path) -> pd.DataFrame | None:
    if not split_artifact.exists():
        return None
    return pd.read_parquet(split_artifact)


def assign_cv_folds_from_artifact(
    df: pd.DataFrame, split_df: pd.DataFrame
) -> pd.DataFrame:
    result = assign_time_groups(df)
    merge_columns = ["row_id", "cv_fold"]
    optional_columns = ["strict_group", "spatial_group", "time_group"]
    for column in optional_columns:
        if column in split_df.columns:
            merge_columns.append(column)
    overlapping_columns = [
        column
        for column in optional_columns
        if column in result.columns and column in split_df.columns
    ]
    if overlapping_columns:
        result = result.drop(columns=overlapping_columns)
    result = result.merge(
        split_df[merge_columns],
        on="row_id",
        how="left",
    )
    missing_mask = result["cv_fold"].isna()
    missing = int(missing_mask.sum())
    if missing > 0:
        raise ValueError(f"Split artifact missing cv_fold for {missing} rows")
    result["cv_fold"] = result["cv_fold"].astype(int)
    return result


def within_10pct(y_true_log: np.ndarray, y_pred_log: np.ndarray) -> float:
    y_true = np.expm1(y_true_log)
    y_pred = np.expm1(y_pred_log)
    denom = np.maximum(y_true, 1.0)
    return float(np.mean(np.abs(y_pred - y_true) / denom <= 0.10) * 100)


def metric_bundle(y_true_log: np.ndarray, y_pred_log: np.ndarray) -> dict[str, float]:
    metrics = compute_metrics(y_true_log, y_pred_log, is_log=True)
    metrics["within_10pct"] = within_10pct(y_true_log, y_pred_log)
    return {key: float(value) for key, value in metrics.items()}


def slice_metrics(
    df: pd.DataFrame, preds: np.ndarray, labels: Sequence[str]
) -> dict[str, dict[str, float]]:
    output: dict[str, dict[str, float]] = {}
    target = df["target_log_price"].to_numpy()

    def add_slice(name: str, mask: pd.Series) -> None:
        if int(mask.sum()) == 0:
            return
        output[name] = metric_bundle(target[mask.to_numpy()], preds[mask.to_numpy()])

    add_slice("overall", pd.Series(np.ones(len(df), dtype=bool), index=df.index))
    add_slice("treasury", df["source_type"] == "treasury")
    add_slice("listing", df["source_type"] == "listing")
    for source_site in sorted(df["source_site"].dropna().unique()):
        add_slice(f"source_{source_site}", df["source_site"] == source_site)
    add_slice("has_images", df["has_images"] == 1)
    add_slice("no_images", df["has_images"] == 0)
    for property_type in labels:
        add_slice(
            f"property_{property_type}",
            df["property_type"] == property_type,
        )
    return output


def flatten_metrics(
    prefix: str, metrics: dict[str, dict[str, float]]
) -> dict[str, float]:
    flat: dict[str, float] = {}
    for slice_name, slice_metrics_dict in metrics.items():
        for metric_name, value in slice_metrics_dict.items():
            flat[f"{prefix}_{slice_name}_{metric_name}"] = float(value)
    return flat


def prepare_feature_matrix(df: pd.DataFrame, feature_cols: list[str]) -> pd.DataFrame:
    feature_df = pd.DataFrame(df[feature_cols].copy())
    for column in feature_cols:
        feature_df[column] = pd.to_numeric(feature_df[column], errors="coerce")
    feature_df = pd.DataFrame(feature_df.astype(float))
    feature_df = pd.DataFrame(feature_df.fillna(0.0))
    return feature_df


def cross_validate(
    df: pd.DataFrame,
    feature_cols: list[str],
    n_folds: int,
    max_listing_test_groups: int,
    source_weights: dict[str, float] | None = None,
    split_df: pd.DataFrame | None = None,
    pretrain_df: pd.DataFrame | None = None,
    pretrain_source_weights: dict[str, float] | None = None,
    pretrain_n_estimators: int = 300,
    finetune_n_estimators: int = 300,
) -> tuple[np.ndarray, dict[str, Any], list[dict[str, Any]]]:
    _ = max_listing_test_groups
    if split_df is not None:
        work_df = assign_cv_folds_from_artifact(df, split_df)
    else:
        work_df = assign_cv_folds(df, n_folds=n_folds)
    X = prepare_feature_matrix(work_df, feature_cols)
    y = work_df["target_log_price"].to_numpy()
    sample_weights = build_sample_weights(work_df, source_weights)
    oof_preds = np.zeros(len(work_df), dtype=float)
    fold_reports: list[dict[str, Any]] = []

    pretrain_work_df = pretrain_df.copy() if pretrain_df is not None else None
    pretrain_X: Any = None
    pretrain_y: np.ndarray | None = None
    pretrain_weights: np.ndarray | None = None
    if pretrain_work_df is not None:
        pretrain_X = prepare_feature_matrix(pretrain_work_df, feature_cols)
        pretrain_y = pretrain_work_df["target_log_price"].to_numpy()
        pretrain_weights = build_sample_weights(
            pretrain_work_df, pretrain_source_weights
        )

    params = DEFAULT_PARAMS.copy()
    params["n_estimators"] = finetune_n_estimators

    pretrain_params = DEFAULT_PARAMS.copy()
    pretrain_params["n_estimators"] = pretrain_n_estimators

    property_counts = work_df["property_type"].value_counts().head(3)
    top_property_types: Sequence[str] = [
        str(value) for value in property_counts.index.to_list()
    ]
    forward_chaining = split_df is not None and "time_group" in split_df.columns
    available_folds = sorted(int(value) for value in work_df["cv_fold"].unique())

    for fold_index in available_folds:
        val_mask = work_df["cv_fold"] == fold_index
        if forward_chaining:
            train_mask = work_df["cv_fold"] < fold_index
        else:
            train_mask = ~val_mask
        if val_mask.sum() == 0 or train_mask.sum() == 0:
            continue

        train_index = np.where(train_mask.to_numpy())[0]
        val_index = np.where(val_mask.to_numpy())[0]

        model = lgb.LGBMRegressor(**params)
        fit_kwargs: dict[str, Any] = {
            "eval_set": [(X.iloc[val_index], y[val_index])],
            "callbacks": [lgb.early_stopping(50, verbose=False)],
        }
        if sample_weights is not None:
            fit_kwargs["sample_weight"] = sample_weights[train_index]
        pretrain_rows_used = 0
        pretrain_rows_excluded = 0
        if (
            pretrain_work_df is not None
            and pretrain_X is not None
            and pretrain_y is not None
            and len(pretrain_work_df) > 0
        ):
            val_row_ids = work_df.iloc[val_index]["row_id"].astype(str).tolist()
            pretrain_mask = ~pretrain_work_df["row_id"].astype(str).isin(val_row_ids)
            pretrain_index = np.where(pretrain_mask.to_numpy())[0]
            pretrain_rows_used = int(len(pretrain_index))
            pretrain_rows_excluded = int((~pretrain_mask).sum())
            if pretrain_rows_used > 0:
                pretrain_model = lgb.LGBMRegressor(**pretrain_params)
                pretrain_fit_kwargs: dict[str, Any] = {}
                if pretrain_weights is not None:
                    pretrain_fit_kwargs["sample_weight"] = pretrain_weights[
                        pretrain_index
                    ]
                pretrain_model.fit(
                    pretrain_X.iloc[pretrain_index],
                    pretrain_y[pretrain_index],
                    **pretrain_fit_kwargs,
                )
                fit_kwargs["init_model"] = pretrain_model.booster_
        model.fit(
            X.iloc[train_index],
            y[train_index],
            **fit_kwargs,
        )

        raw_preds = model.predict(X.iloc[val_index])
        val_preds = np.asarray(raw_preds, dtype=float)
        oof_preds[val_index] = val_preds

        fold_df = work_df.iloc[val_index].copy()
        slices = slice_metrics(fold_df, val_preds, top_property_types)
        fold_reports.append(
            {
                "fold": fold_index + 1,
                "cv_fold": int(fold_index),
                "treasury_time_groups": sorted(
                    fold_df.loc[
                        fold_df["source_type"] == "treasury", "time_group"
                    ].unique()
                ),
                "listing_groups": int(
                    fold_df.loc[
                        fold_df["source_type"] == "listing", "duplicate_group"
                    ].nunique()
                ),
                "strict_groups": int(fold_df["strict_group"].nunique())
                if "strict_group" in fold_df.columns
                else None,
                "spatial_groups": int(fold_df["spatial_group"].nunique())
                if "spatial_group" in fold_df.columns
                else None,
                "rows": int(len(fold_df)),
                "pretrain_rows_used": pretrain_rows_used,
                "pretrain_rows_excluded_for_overlap": pretrain_rows_excluded,
                "metrics": slices,
            }
        )
        logger.info(
            "Fold %s rows=%s pretrain_rows=%s overall_mae=%.0f listing_mae=%s treasury_mae=%s",
            fold_index + 1,
            len(fold_df),
            pretrain_rows_used,
            slices["overall"]["mae"],
            f"{slices.get('listing', {}).get('mae', float('nan')):.0f}"
            if "listing" in slices
            else "n/a",
            f"{slices.get('treasury', {}).get('mae', float('nan')):.0f}"
            if "treasury" in slices
            else "n/a",
        )

    overall_slices = slice_metrics(
        work_df.loc[oof_preds != 0.0].copy() if forward_chaining else work_df,
        np.asarray(oof_preds[oof_preds != 0.0], dtype=float)
        if forward_chaining
        else np.asarray(oof_preds, dtype=float),
        [str(value) for value in top_property_types],
    )
    return oof_preds, overall_slices, fold_reports


def save_outputs(
    output_dir: Path,
    dataset: pd.DataFrame,
    predictions: np.ndarray,
    stage: str,
    feature_cols: list[str],
    metrics: dict[str, Any],
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    prediction_df = dataset.copy()
    prediction_df["predicted_log_price"] = predictions
    prediction_df["predicted_price_thb"] = np.expm1(predictions)
    prediction_df["abs_error_thb"] = np.abs(
        prediction_df["predicted_price_thb"] - prediction_df["target_price_thb"]
    )

    prediction_df.to_parquet(output_dir / f"predictions_{stage}.parquet", index=False)
    (output_dir / f"features_{stage}.json").write_text(
        json.dumps(feature_cols, indent=2), encoding="utf-8"
    )
    (output_dir / f"metrics_{stage}.json").write_text(
        json.dumps(metrics, indent=2), encoding="utf-8"
    )


def train_stage(args: argparse.Namespace, stage: str) -> dict[str, Any]:
    raw_dataset = pd.read_parquet(args.dataset)
    raw_dataset = merge_image_embeddings(raw_dataset, args.image_embeddings)
    raw_pretrain_dataset = (
        pd.read_parquet(args.pretrain_dataset)
        if args.pretrain_dataset is not None
        else None
    )
    if raw_pretrain_dataset is not None:
        raw_pretrain_dataset = merge_image_embeddings(
            raw_pretrain_dataset, args.image_embeddings
        )
    category_maps = build_category_maps(
        [df for df in [raw_dataset, raw_pretrain_dataset] if df is not None]
    )
    dataset, feature_cols = build_feature_set(
        raw_dataset, stage, category_maps=category_maps
    )
    pretrain_dataset: pd.DataFrame | None = None
    if raw_pretrain_dataset is not None:
        pretrain_dataset, _ = build_feature_set(
            raw_pretrain_dataset,
            stage,
            category_maps=category_maps,
        )
        for column in feature_cols:
            if column not in pretrain_dataset.columns:
                pretrain_dataset[column] = np.nan
        pretrain_dataset = pretrain_dataset.reset_index(drop=True)
    split_df = load_split_artifact(args.split_artifact)
    source_weights = load_source_weights(args.source_weights_json)
    pretrain_source_weights = load_source_weights(args.pretrain_source_weights_json)
    predictions, slice_report, fold_reports = cross_validate(
        dataset,
        feature_cols=feature_cols,
        n_folds=args.cv_folds,
        max_listing_test_groups=args.max_listing_test_groups,
        source_weights=source_weights,
        split_df=split_df,
        pretrain_df=pretrain_dataset,
        pretrain_source_weights=pretrain_source_weights,
        pretrain_n_estimators=args.pretrain_n_estimators,
        finetune_n_estimators=args.finetune_n_estimators,
    )

    metrics = {
        "stage": stage,
        "split_artifact": str(args.split_artifact) if split_df is not None else None,
        "feature_count": len(feature_cols),
        "feature_cols": feature_cols,
        "source_weights": source_weights,
        "pretrain_dataset": str(args.pretrain_dataset)
        if args.pretrain_dataset is not None
        else None,
        "pretrain_source_weights": pretrain_source_weights
        if args.pretrain_dataset is not None
        else None,
        "pretrain_n_estimators": args.pretrain_n_estimators
        if args.pretrain_dataset is not None
        else 0,
        "finetune_n_estimators": args.finetune_n_estimators,
        "pretrain_rows": int(len(pretrain_dataset))
        if pretrain_dataset is not None
        else 0,
        "image_embeddings": str(args.image_embeddings)
        if args.image_embeddings is not None and args.image_embeddings.exists()
        else None,
        "slices": slice_report,
        "folds": fold_reports,
    }
    save_outputs(args.output_dir, dataset, predictions, stage, feature_cols, metrics)
    return metrics


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    stages = [stage.strip() for stage in args.stages.split(",") if stage.strip()]
    if not stages:
        raise ValueError("At least one stage must be provided via --stages")

    experiment_name = args.experiment or get_experiment_name("baseline")
    tags = DEFAULT_TAGS.copy()
    tags.update(
        {
            "pipeline": "combined-price",
            "benchmark_type": "combined-source",
            "training_strategy": "two-stage"
            if args.pretrain_dataset is not None
            else "single-stage",
        }
    )

    run_context = build_standard_run_context(
        model_family="combined_price",
        model_variant="cpu_phase_a_two_stage"
        if args.pretrain_dataset is not None
        else "cpu_phase_a",
        feature_set="C1_to_C5I" if "C5I" in stages else "C1_to_C5",
        target="target_log_price",
        split_seed=42,
        dataset_version=args.dataset_version,
    )

    all_results: dict[str, Any] = {}
    with mlflow_run(
        experiment_name=experiment_name,
        run_name=args.run_name,
        tracking_uri=args.tracking_uri,
        tags=tags,
    ):
        log_standard_run_context(run_context)
        log_params_safe(
            {
                "dataset": str(args.dataset),
                "split_artifact": str(args.split_artifact),
                "dataset_version": args.dataset_version,
                "cv_folds": args.cv_folds,
                "max_listing_test_groups": args.max_listing_test_groups,
                "source_weights_json": str(args.source_weights_json)
                if args.source_weights_json is not None
                else "default",
                "pretrain_dataset": str(args.pretrain_dataset)
                if args.pretrain_dataset is not None
                else "none",
                "pretrain_source_weights_json": str(args.pretrain_source_weights_json)
                if args.pretrain_source_weights_json is not None
                else "default",
                "pretrain_n_estimators": args.pretrain_n_estimators,
                "finetune_n_estimators": args.finetune_n_estimators,
                "image_embeddings": str(args.image_embeddings)
                if args.image_embeddings is not None and args.image_embeddings.exists()
                else "none",
                "stages": ",".join(stages),
            }
        )

        for stage in stages:
            logger.info("Training stage %s", stage)
            metrics = train_stage(args, stage)
            all_results[stage] = metrics
            flattened = flatten_metrics(stage.lower(), metrics["slices"])
            flattened[f"{stage.lower()}_feature_count"] = float(
                metrics["feature_count"]
            )
            log_metrics_safe(flattened)
            set_tag_safe(f"best_available_stage", stage)
            log_artifact_safe(
                args.output_dir / f"metrics_{stage}.json", artifact_path="metrics"
            )
            log_artifact_safe(
                args.output_dir / f"features_{stage}.json", artifact_path="config"
            )

        summary_path = args.output_dir / "stage_summary.json"
        summary_path.write_text(json.dumps(all_results, indent=2), encoding="utf-8")
        log_artifact_safe(summary_path, artifact_path="metrics")
        logger.info("Saved stage summary to %s", summary_path)


if __name__ == "__main__":
    main()
