/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedValuationRouteImport } from './routes/_authenticated/valuation'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDistrictsRouteImport } from './routes/_authenticated/districts'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedSiteSiteIdRouteImport } from './routes/_authenticated/site/$siteId'
import { Route as AuthenticatedPropertyPropertyIdRouteImport } from './routes/_authenticated/property/$propertyId'
import { Route as AuthenticatedChatSessionIdRouteImport } from './routes/_authenticated/chat/$sessionId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedValuationRoute = AuthenticatedValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDistrictsRoute = AuthenticatedDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSiteSiteIdRoute = AuthenticatedSiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertyPropertyIdRoute =
  AuthenticatedPropertyPropertyIdRouteImport.update({
    id: '/property/$propertyId',
    path: '/property/$propertyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatSessionIdRoute =
  AuthenticatedChatSessionIdRouteImport.update({
    id: '/chat/$sessionId',
    path: '/chat/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/districts': typeof AuthenticatedDistrictsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/valuation': typeof AuthenticatedValuationRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/property/$propertyId': typeof AuthenticatedPropertyPropertyIdRoute
  '/site/$siteId': typeof AuthenticatedSiteSiteIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/districts': typeof AuthenticatedDistrictsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/valuation': typeof AuthenticatedValuationRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/property/$propertyId': typeof AuthenticatedPropertyPropertyIdRoute
  '/site/$siteId': typeof AuthenticatedSiteSiteIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/districts': typeof AuthenticatedDistrictsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/valuation': typeof AuthenticatedValuationRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/_authenticated/property/$propertyId': typeof AuthenticatedPropertyPropertyIdRoute
  '/_authenticated/site/$siteId': typeof AuthenticatedSiteSiteIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/districts'
    | '/settings'
    | '/valuation'
    | '/login'
    | '/register'
    | '/'
    | '/chat/$sessionId'
    | '/property/$propertyId'
    | '/site/$siteId'
    | '/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/districts'
    | '/settings'
    | '/valuation'
    | '/login'
    | '/register'
    | '/'
    | '/chat/$sessionId'
    | '/property/$propertyId'
    | '/site/$siteId'
    | '/chat'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/districts'
    | '/_authenticated/settings'
    | '/_authenticated/valuation'
    | '/_public/login'
    | '/_public/register'
    | '/_authenticated/'
    | '/_authenticated/chat/$sessionId'
    | '/_authenticated/property/$propertyId'
    | '/_authenticated/site/$siteId'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/valuation': {
      id: '/_authenticated/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof AuthenticatedValuationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/districts': {
      id: '/_authenticated/districts'
      path: '/districts'
      fullPath: '/districts'
      preLoaderRoute: typeof AuthenticatedDistrictsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/site/$siteId': {
      id: '/_authenticated/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof AuthenticatedSiteSiteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/property/$propertyId': {
      id: '/_authenticated/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertyPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$sessionId': {
      id: '/_authenticated/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AuthenticatedChatSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDistrictsRoute: typeof AuthenticatedDistrictsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedValuationRoute: typeof AuthenticatedValuationRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatSessionIdRoute: typeof AuthenticatedChatSessionIdRoute
  AuthenticatedPropertyPropertyIdRoute: typeof AuthenticatedPropertyPropertyIdRoute
  AuthenticatedSiteSiteIdRoute: typeof AuthenticatedSiteSiteIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDistrictsRoute: AuthenticatedDistrictsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedValuationRoute: AuthenticatedValuationRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChatSessionIdRoute: AuthenticatedChatSessionIdRoute,
  AuthenticatedPropertyPropertyIdRoute: AuthenticatedPropertyPropertyIdRoute,
  AuthenticatedSiteSiteIdRoute: AuthenticatedSiteSiteIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
